export const messages = {
  en: {
    privacy: "Stored securely on this computer. Nothing is uploaded.",
    profiles: "Your profiles",
    search: "Search profiles",
    add: "Add profile",
    settings: "Settings",
    lock: "Lock app",
    emptyTitle: "Your private document vault is ready",
    emptyBody:
      "Add an identity card once, then create purpose-marked copies whenever you need them.",
    create: "Create profile",
    name: "Profile name",
    label: "Document label (optional)",
    cancel: "Cancel",
    modified: "Modified",
    open: "Open",
    edit: "Edit",
    delete: "Delete",
    rename: "Rename profile",
    sortModified: "Last modified",
    sortName: "Name",
    sortCustom: "Custom order",
    back: "Back to profiles",
    front: "Front",
    backSide: "Back",
    addBack: "Add back image",
    addBackBody: "Add the back of the document, or leave this side empty.",
    replace: "Replace image",
    removeBack: "Remove back",
    confirmRemoveBack: "Remove the back image and its saved settings?",
    watermark: "Watermark text",
    watermarkSettings: "watermark settings",
    sideSpecific: "Changes apply only to this side.",
    copyToBack: "Copy watermark to back",
    copyToFront: "Copy watermark to front",
    opacity: "Opacity",
    size: "Text size",
    rotation: "Rotation",
    rotateImageLeft: "Rotate image left 90°",
    rotateImageRight: "Rotate image right 90°",
    rotateWatermarkLeft: "Rotate watermark left 5°",
    rotateWatermarkRight: "Rotate watermark right 5°",
    lines: "Crossing lines",
    color: "Colour",
    date: "Add today’s date",
    uppercase: "Uppercase",
    reset: "Recommended layout",
    presets: "Presets",
    savePreset: "Save as preset",
    export: "Export",
    frontOnly: "Front only",
    backOnly: "Back only",
    combined: "Front + back stacked",
    copy: "Copy image",
    format: "Format",
    quality: "Quality",
    unlock: "Unlock Palang IC",
    password: "Password",
    unlockButton: "Unlock",
    noRecovery:
      "Palang IC cannot recover this password. If you forget it, you will lose access to the stored profiles.",
    general: "General",
    security: "Security",
    backup: "Backup & restore",
    language: "Language",
    appearance: "Appearance",
    themeSystem: "Use device setting",
    themeLight: "Light",
    themeDark: "Dark",
    enablePassword: "Enable application password",
    changePassword: "Change password",
    disablePassword: "Disable password",
    autoLock: "Automatically lock",
    minimized: "Lock when minimized",
    createBackup: "Export encrypted backup",
    restoreBackup: "Import encrypted backup",
    backupPassword: "Backup password",
    deleteAll: "Delete all local data",
    deleteWarning:
      "This permanently deletes all saved profiles and identity-card images from this computer.",
    done: "Done",
    save: "Save",
    error: "Something went wrong",
    confirmDelete: "Delete this profile and its encrypted images?",
    confirmDeleteAll: "Permanently delete every profile and local image?",
    exportSaved: "Export saved successfully.",
    backupSaved: "Encrypted backup created.",
    restored: "Backup restored.",
    addFrontTitle: "Add the front image",
    addFrontBody:
      "Your profile is ready. Add the front of the document to begin editing.",
    chooseFrontImage: "Choose front image",
    textAlign: "Alignment",
    lineThickness: "Line thickness",
    lineOpacity: "Line opacity",
    recent: "Recent",
    never: "Never",
    minute: "1 minute",
    minutes5: "5 minutes",
    minutes15: "15 minutes",
    minutes30: "30 minutes",
    high: "High",
    standard: "Standard",
    maximum: "Maximum",
    passwordConfirm: "Confirm password",
    conflict: "When names conflict",
    keep: "Keep existing",
    replaceExisting: "Replace existing",
    importCopy: "Import as a copy",
    about: "About",
    aboutBody:
      "Palang IC works offline. Identity images, profile names, and watermark text are never sent to Palang IC servers.",
    website: "Visit website",
    close: "Close",
    prepareImage: "Crop",
    cropImage: "Crop image",
    cropInstructions:
      "Drag the frame or its handles. Scroll or pinch to zoom. Arrow keys move; Alt/Option + arrows resize the top or left edge, and add Shift for the bottom or right edge.",
    cropArea: "Interactive crop area",
    cropResolution: "Output",
    cropTooSmall:
      "Zoom out, enlarge the frame, rotate back, or use a larger image (minimum 300 × 180 px).",
    imageAdjustments: "Image adjustments",
    cropZoom: "Crop zoom",
    cropZoomIn: "Zoom crop in",
    cropZoomOut: "Zoom crop out",
    cropShape: "Crop shape",
    freeCrop: "Free",
    originalImage: "Full image",
    resetCrop: "Reset",
    rotateLeft: "Rotate left",
    rotateRight: "Rotate right",
    flipHorizontal: "Flip horizontally",
    idRatio: "ID card",
    confirm: "Confirm",
    paste: "Paste image",
    dropHint: "Drop an image here, paste from the clipboard, or choose a file.",
    duplicate: "Duplicate",
    moveUp: "Move up",
    moveDown: "Move down",
    managePresets: "Manage presets",
    presetName: "Preset name",
    updatePreset: "Update preset",
    deletePreset: "Delete preset",
    currentPassword: "Current password",
    newPassword: "New password",
    changePasswordDone: "Password changed.",
    separate: "Separate image files",
    openFile: "Open file",
    showFolder: "Show in folder",
    defaultFolder: "Default export folder",
    chooseFolder: "Choose folder",
    selectBackup: "Select backup file",
    inspectBackup: "Check password and show profiles",
    selectAll: "Select all profiles",
    restoreSelected: "Restore selected profiles",
    corruptImage:
      "Palang IC could not open this stored image. You can replace it while keeping the profile.",
    lineWidth: "Line width",
    editorControls: "Editor controls",
    editing: "Editing",
    documentPreview: "Document preview",
    imageControls: "Image",
    imageActions: "Image actions",
    imageSettings: "image settings",
    imageSettingsNote: "This zoom is saved separately for the active side.",
    imageZoom: "Image zoom",
    zoomOut: "Zoom image out",
    zoomIn: "Zoom image in",
    watermarkControl: "Watermark",
    more: "More",
    decreaseSize: "Decrease watermark size",
    increaseSize: "Increase watermark size",
    moreWatermarkSettings: "More watermark settings",
    crossingLineControls: "Crossing line controls",
    watermarkGesturesHint:
      "Choose Watermark, then select and drag it. Pinch with two fingers to resize it. When the preview is focused, use the arrow keys to move the watermark; hold Shift for smaller steps.",
    resetWatermark: "Reset watermark",
    qualityWarning:
      "This image may be small or blurry. Check that all details remain readable before exporting.",
    checkUpdates: "Check for updates",
    support: "Support",
    version: "Version",
    licenses: "Open-source licence notices",
    forgotPassword: "Forgot password?",
    resetVault: "Reset and delete inaccessible vault",
    confirmResetVault:
      "This permanently deletes the locked vault and every stored identity image. This cannot be undone.",
    privateVault: "Private vault",
    sort: "Sort profiles",
    identityCard: "Identity card",
    documentPlaceholder: "MyKad, driving licence…",
    alignLeft: "Left",
    alignCenter: "Centre",
    alignRight: "Right",
    lineSpacing: "Line spacing",
    incorrectPassword: "Incorrect password.",
    passwordRules: "Passwords must match and contain at least 8 characters.",
    damagedBackup: "Incorrect password or damaged backup.",
  },
  ms: {
    privacy:
      "Disimpan dengan selamat pada komputer ini. Tiada apa-apa dimuat naik.",
    profiles: "Profil anda",
    search: "Cari profil",
    add: "Tambah profil",
    settings: "Tetapan",
    lock: "Kunci aplikasi",
    emptyTitle: "Peti dokumen peribadi anda sedia",
    emptyBody:
      "Tambah kad pengenalan sekali, kemudian cipta salinan bertanda tujuan apabila diperlukan.",
    create: "Cipta profil",
    name: "Nama profil",
    label: "Label dokumen (pilihan)",
    cancel: "Batal",
    modified: "Diubah",
    open: "Buka",
    edit: "Edit",
    delete: "Padam",
    rename: "Namakan semula profil",
    sortModified: "Terakhir diubah",
    sortName: "Nama",
    sortCustom: "Susunan sendiri",
    back: "Kembali ke profil",
    front: "Hadapan",
    backSide: "Belakang",
    addBack: "Tambah imej belakang",
    addBackBody:
      "Tambah bahagian belakang dokumen, atau biarkan sisi ini kosong.",
    replace: "Ganti imej",
    removeBack: "Buang belakang",
    confirmRemoveBack: "Buang imej belakang dan tetapan tersimpannya?",
    watermark: "Teks tanda air",
    watermarkSettings: "tetapan tanda air",
    sideSpecific: "Perubahan hanya digunakan pada sisi ini.",
    copyToBack: "Salin tanda air ke belakang",
    copyToFront: "Salin tanda air ke hadapan",
    opacity: "Kelegapan",
    size: "Saiz teks",
    rotation: "Putaran",
    rotateImageLeft: "Putar imej 90° ke kiri",
    rotateImageRight: "Putar imej 90° ke kanan",
    rotateWatermarkLeft: "Putar tanda air 5° ke kiri",
    rotateWatermarkRight: "Putar tanda air 5° ke kanan",
    lines: "Garisan palang",
    color: "Warna",
    date: "Tambah tarikh hari ini",
    uppercase: "Huruf besar",
    reset: "Susun atur disyorkan",
    presets: "Pratetap",
    savePreset: "Simpan sebagai pratetap",
    export: "Eksport",
    frontOnly: "Hadapan sahaja",
    backOnly: "Belakang sahaja",
    combined: "Hadapan + belakang bertindan",
    copy: "Salin imej",
    format: "Format",
    quality: "Kualiti",
    unlock: "Buka kunci Palang IC",
    password: "Kata laluan",
    unlockButton: "Buka kunci",
    noRecovery:
      "Palang IC tidak boleh memulihkan kata laluan ini. Jika terlupa, anda akan kehilangan akses kepada profil yang disimpan.",
    general: "Umum",
    security: "Keselamatan",
    backup: "Sandaran & pemulihan",
    language: "Bahasa",
    appearance: "Penampilan",
    themeSystem: "Gunakan tetapan peranti",
    themeLight: "Cerah",
    themeDark: "Gelap",
    enablePassword: "Aktifkan kata laluan aplikasi",
    changePassword: "Tukar kata laluan",
    disablePassword: "Nyahaktif kata laluan",
    autoLock: "Kunci secara automatik",
    minimized: "Kunci apabila diminimumkan",
    createBackup: "Eksport sandaran disulitkan",
    restoreBackup: "Import sandaran disulitkan",
    backupPassword: "Kata laluan sandaran",
    deleteAll: "Padam semua data setempat",
    deleteWarning:
      "Ini akan memadam semua profil dan imej kad pengenalan pada komputer ini secara kekal.",
    done: "Selesai",
    save: "Simpan",
    error: "Sesuatu tidak kena",
    confirmDelete: "Padam profil ini dan imej yang disulitkan?",
    confirmDeleteAll: "Padam semua profil dan imej setempat secara kekal?",
    exportSaved: "Eksport berjaya disimpan.",
    backupSaved: "Sandaran disulitkan telah dicipta.",
    restored: "Sandaran dipulihkan.",
    addFrontTitle: "Tambah imej hadapan",
    addFrontBody:
      "Profil anda sudah tersedia. Tambah bahagian hadapan dokumen untuk mula menyunting.",
    chooseFrontImage: "Pilih imej hadapan",
    textAlign: "Penjajaran",
    lineThickness: "Ketebalan garisan",
    lineOpacity: "Kelegapan garisan",
    recent: "Terkini",
    never: "Tidak pernah",
    minute: "1 minit",
    minutes5: "5 minit",
    minutes15: "15 minit",
    minutes30: "30 minit",
    high: "Tinggi",
    standard: "Standard",
    maximum: "Maksimum",
    passwordConfirm: "Sahkan kata laluan",
    conflict: "Apabila nama bertindih",
    keep: "Kekalkan yang sedia ada",
    replaceExisting: "Ganti yang sedia ada",
    importCopy: "Import sebagai salinan",
    about: "Perihal",
    aboutBody:
      "Palang IC berfungsi di luar talian. Imej identiti, nama profil dan teks tanda air tidak pernah dihantar ke pelayan Palang IC.",
    website: "Lawati laman web",
    close: "Tutup",
    prepareImage: "Potong",
    cropImage: "Potong imej",
    cropInstructions:
      "Seret bingkai atau pemegangnya. Tatal atau cubit untuk zum. Kekunci anak panah mengalih; Alt/Option + anak panah mengubah saiz tepi atas atau kiri, dan tambah Shift untuk tepi bawah atau kanan.",
    cropArea: "Kawasan potongan interaktif",
    cropResolution: "Output",
    cropTooSmall:
      "Zum keluar, besarkan bingkai, putar semula atau gunakan imej lebih besar (minimum 300 × 180 px).",
    imageAdjustments: "Pelarasan imej",
    cropZoom: "Zum potongan",
    cropZoomIn: "Zum masuk potongan",
    cropZoomOut: "Zum keluar potongan",
    cropShape: "Bentuk potongan",
    freeCrop: "Bebas",
    originalImage: "Imej penuh",
    resetCrop: "Tetapkan semula",
    rotateLeft: "Putar kiri",
    rotateRight: "Putar kanan",
    flipHorizontal: "Terbalik mendatar",
    idRatio: "Kad pengenalan",
    confirm: "Sahkan",
    paste: "Tampal imej",
    dropHint:
      "Lepaskan imej di sini, tampal daripada papan klip atau pilih fail.",
    duplicate: "Duplikasi",
    moveUp: "Alih ke atas",
    moveDown: "Alih ke bawah",
    managePresets: "Urus pratetap",
    presetName: "Nama pratetap",
    updatePreset: "Kemas kini pratetap",
    deletePreset: "Padam pratetap",
    currentPassword: "Kata laluan semasa",
    newPassword: "Kata laluan baharu",
    changePasswordDone: "Kata laluan ditukar.",
    separate: "Fail imej berasingan",
    openFile: "Buka fail",
    showFolder: "Tunjukkan dalam folder",
    defaultFolder: "Folder eksport lalai",
    chooseFolder: "Pilih folder",
    selectBackup: "Pilih fail sandaran",
    inspectBackup: "Semak kata laluan dan tunjukkan profil",
    selectAll: "Pilih semua profil",
    restoreSelected: "Pulihkan profil terpilih",
    corruptImage:
      "Palang IC tidak dapat membuka imej tersimpan ini. Anda boleh menggantikannya tanpa memadam profil.",
    lineWidth: "Lebar garisan",
    editorControls: "Kawalan penyunting",
    editing: "Sedang disunting",
    documentPreview: "Pratonton dokumen",
    imageControls: "Imej",
    imageActions: "Tindakan imej",
    imageSettings: "tetapan imej",
    imageSettingsNote: "Zum ini disimpan secara berasingan untuk sisi aktif.",
    imageZoom: "Zum imej",
    zoomOut: "Zum keluar imej",
    zoomIn: "Zum masuk imej",
    watermarkControl: "Tanda air",
    more: "Lagi",
    decreaseSize: "Kecilkan tanda air",
    increaseSize: "Besarkan tanda air",
    moreWatermarkSettings: "Lagi tetapan tanda air",
    crossingLineControls: "Kawalan garisan silang",
    watermarkGesturesHint:
      "Pilih Tanda air, kemudian pilih dan seret tanda air itu. Cubit dengan dua jari untuk mengubah saiznya. Apabila pratonton difokuskan, gunakan kekunci anak panah untuk mengalih tanda air; tahan Shift untuk langkah yang lebih kecil.",
    resetWatermark: "Tetapkan semula tanda air",
    qualityWarning:
      "Imej ini mungkin kecil atau kabur. Pastikan semua butiran boleh dibaca sebelum mengeksport.",
    checkUpdates: "Semak kemas kini",
    support: "Sokongan",
    version: "Versi",
    licenses: "Notis lesen sumber terbuka",
    forgotPassword: "Lupa kata laluan?",
    resetVault: "Tetapkan semula dan padam peti yang tidak boleh dibuka",
    confirmResetVault:
      "Ini akan memadam peti terkunci dan semua imej identiti secara kekal. Tindakan ini tidak boleh dibatalkan.",
    privateVault: "Peti peribadi",
    sort: "Susun profil",
    identityCard: "Kad pengenalan",
    documentPlaceholder: "MyKad, lesen memandu…",
    alignLeft: "Kiri",
    alignCenter: "Tengah",
    alignRight: "Kanan",
    lineSpacing: "Jarak baris",
    incorrectPassword: "Kata laluan tidak betul.",
    passwordRules: "Kata laluan mesti sepadan dan sekurang-kurangnya 8 aksara.",
    damagedBackup: "Kata laluan salah atau sandaran rosak.",
  },
} as const;

export type MessageKey = keyof typeof messages.en;
